In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re
import datetime as dt

In [2]:
data_alycbur = pd.read_excel('/Applications/Python 3.10/Data Science Coursera/Operaciones Alycbur.xlsx', header=3)
clientes = pd.read_excel('/Applications/Python 3.10/Data Science Coursera/Listado Clientes Operados.xlsx')
operaciones = pd.read_excel('/Applications/Python 3.10/Data Science Coursera/Listado Categorias Operaciones.xlsx')

data_alycbur['Empresa'] = 'ALYCBUR'
data_alycbur.head()

,Boleto,Concertación,Liquidación,CUIT,Cuenta,Denominación,Cartera,Categoría,Clase,Tipo de operación,...,Aranceles,Gastos,Impuestos,Otros,Tipo de cambio,Administrador,Operador,Situación,Número de Operacion,Empresa
0,BOL 2021000001,2021-01-04,2021-01-04,20-11293684-0,500104,JORGE MIGUEL ROTSTEIN,[GRUPO 5] GRUPO 5,NaN,NaN,SENEBI Contado - Venta,...,0,0,0,0,NaN,NaN,NaN,NaN,37,ALYCBUR
1,BOL 2021000002,2021-01-04,2021-01-04,30-71436632-3,499999,ALYCBUR S.A.,NaN,NaN,NaN,SENEBI Contado - Compra,...,0,"ARS 1840,03",0,0,NaN,NaN,NaN,NaN,11975,ALYCBUR
2,BOL 2021000003,2021-01-04,2021-01-06,20-93219129-7,310012,JOVANOVICH KIRKO,[GRUPO 3] GRUPO 3,NaN,NaN,Concurrencia Contado - Compra,...,"ARS 380,60","ARS 30,45","ARS 86,32",0,NaN,PROD3 - PRODUCTOR GRUPO 3,NaN,NaN,113,ALYCBUR
3,BOL 2021000004 (A),2021-01-04,2021-01-06,20-25554902-3,120239,REGALADO JUAN PABLO,[GRUPO 1] GRUPO 1,NaN,NaN,Concurrencia Contado - Compra,...,"ARS 692,00","ARS 55,36","ARS 156,95",0,NaN,PROD1 - PRODUCTOR GRUPO 1,NaN,NaN,114,ALYCBUR
4,BOL 2021000005 (A),2021-01-04,2021-01-04,20-11293684-0,500104,JORGE MIGUEL ROTSTEIN,[GRUPO 5] GRUPO 5,NaN,NaN,Concurrencia Contado - Compra,...,"ARS 174033,04","ARS 1156,68",0,0,"T.C.: USD 1 = ARS 89,25",NaN,NaN,NaN,115,ALYCBUR

In [3]:
operaciones_alycbur = data_alycbur['Tipo de operación'].unique().tolist()
filtro_operaciones = [operacion for operacion in operaciones_alycbur if 'Subasta' in operacion]
filtro_operaciones

['ECHEQ - Subasta', 'CPD - Subasta', 'FCE - Subasta', 'Pagarés - Subasta']

In [4]:
data_alycbur = data_alycbur[data_alycbur['Tipo de operación'].isin(filtro_operaciones)]
data_alycbur = data_alycbur.drop(columns=['Gastos'])
data_alycbur = data_alycbur[(data_alycbur['Denominación']!='ALYCBUR S.A.') & (data_alycbur['Denominación']!='FINARES SA') & (data_alycbur['Denominación']!='ALYCBUR SA') & (data_alycbur['Denominación']!='ADCAP BALANCEADO VIII') & (data_alycbur['Denominación']!='ALYCBUR FONDO COMÚN DE INVERSIÓN ABIERTO PYMES') & (data_alycbur['Denominación']!='GOLDMAN, EDUARDO ELIAS')]
data_alycbur['CUIT'] = data_alycbur['CUIT'].str.replace('-', '').astype(int)
data_alycbur

,Boleto,Concertación,Liquidación,CUIT,Cuenta,Denominación,Cartera,Categoría,Clase,Tipo de operación,...,Neto,Aranceles,Impuestos,Otros,Tipo de cambio,Administrador,Operador,Situación,Número de Operacion,Empresa
54,BOL 2021000055,2021-01-04,2021-01-04,30600725447,500062,"ROWING SA o ROMAN, JESICA",[GRUPO 5] GRUPO 5,NaN,NaN,ECHEQ - Subasta,...,"ARS -409396,42","ARS 11005,06","ARS 15764,50",0,NaN,NaN,NaN,/ARS/,1084,ALYCBUR
57,BOL 2021000058,2021-01-04,2021-01-04,30600725447,500062,"ROWING SA o ROMAN, JESICA",[GRUPO 5] GRUPO 5,NaN,NaN,ECHEQ - Subasta,...,"ARS -218623,75","ARS 5502,64","ARS 5466,29",0,NaN,NaN,NaN,/ARS/,1085,ALYCBUR
59,BOL 2021000060,2021-01-04,2021-01-04,30600725447,500062,"ROWING SA o ROMAN, JESICA",[GRUPO 5] GRUPO 5,NaN,NaN,ECHEQ - Subasta,...,"ARS -218702,20","ARS 5514,52","ARS 5546,40",0,NaN,NaN,NaN,/ARS/,1086,ALYCBUR
61,BOL 2021000062,2021-01-04,2021-01-04,30600725447,500062,"ROWING SA o ROMAN, JESICA",[GRUPO 5] GRUPO 5,NaN,NaN,ECHEQ - Subasta,...,"ARS -305525,68","ARS 7717,60","ARS 7857,53",0,NaN,NaN,NaN,/ARS/,1087,ALYCBUR
63,BOL 2021000064,2021-01-04,2021-01-04,30600725447,500062,"ROWING SA o ROMAN, JESICA",[GRUPO 5] GRUPO 5,NaN,NaN,ECHEQ - Subasta,...,"ARS -303887,25","ARS 7717,60","ARS 8141,88",0,NaN,NaN,NaN,/ARS/,1088,ALYCBUR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67796,BOL 2023005986,2023-03-03,2023-03-03,30708442409,500040,MAXIMIA SA,[GRUPO 5] GRUPO 5,NaN,NaN,ECHEQ - Subasta,...,"ARS -541306,17","ARS 29767,94","ARS 6281,99",0,NaN,NaN,NaN,/ARS/,109502,ALYCBUR
67832,BOL 2023006022,2023-03-03,2023-03-06,30707805338,500226,ATLANTIDA DIGITAL S.A.,[GRUPO 5] GRUPO 5,NaN,NaN,ECHEQ - Subasta,...,"ARS -446075,13","ARS 5000,00","ARS 1082,93",0,NaN,NaN,NaN,/ARS/,109528,ALYCBUR
67833,BOL 2023006023,2023-03-03,2023-03-06,30707805338,500226,ATLANTIDA DIGITAL S.A.,[GRUPO 5] GRUPO 5,NaN,NaN,ECHEQ - Subasta,...,"ARS -451981,01","ARS 5000,00","ARS 1078,87",0,NaN,NaN,NaN,/ARS/,109529,ALYCBUR
67835,BOL 2023006025,2023-03-03,2023-03-06,30707805338,500226,ATLANTIDA DIGITAL S.A.,[GRUPO 5] GRUPO 5,NaN,NaN,ECHEQ - Subasta,...,"ARS -458042,53","ARS 5000,00","ARS 1074,70",0,NaN,NaN,NaN,/ARS/,109531,ALYCBUR
67836,BOL 2023006026,2023-03-03,2023-03-06,30707805338,500226,ATLANTIDA DIGITAL S.A.,[GRUPO 5] GRUPO 5,NaN,NaN,ECHEQ - Subasta,...,"ARS -220159,49","ARS 2500,00","ARS 543,44",0,NaN,NaN,NaN,/ARS/,109532,ALYCBUR

In [5]:
clientes

,CUIT,Cliente,Grupo / Cliente,Oficial,Ubicación
0,30701820335,AEROMEDICAL SA,AEROMEDICAL SA,MATÍAS GOLDARACENA,"Buenos Aires, Argentina"
1,30711827923,FIXON GROUP SA,GRUPO FIXON,CLAUDIA GALLARDO,"Provincia de Entre Ríos, Argentina"
2,30559248092,MARIA LETTIERI SA,MARIA LETTIERI SA,ASISTENCIA COMERCIAL,"Provincia de Buenos Aires, Argentina"
3,30716851628,PLASTICOS Y QUIMICOS FBN SA,PLASTICOS Y QUIMICOS FBN SA,ALEJANDRO POMARADA,"Buenos Aires, Argentina"
4,30685173421,PRO ENTERTAINMENT SA,PRO ENTERTAINMENT SA,SILVIA LÓPEZ,"Buenos Aires, Argentina"
...,...,...,...,...,...
196,30616509361,PECAM S.A.,PECAM S.A.,SEBASTÍAN LÓPEZ,"Santa Fe, Argentina"
197,20255881591,"BERDINI, OMAR DANIEL","BERDINI, OMAR DANIEL",ASISTENCIA COMERCIAL,"Provincia de Corrientes, Argentina"
198,30504005085,FRIAR SA,FRIAR SA,ASISTENCIA COMERCIAL,"Santa Fe, Argentina"
199,30717110761,JF & FEG SRL,JF & FEG SRL,ASISTENCIA COMERCIAL,"Salta, Argentina"
200,30712493174,NFP S.A.,NFP S.A.,ASISTENCIA COMERCIAL,"Buenos Aires, Argentina"

In [6]:
data_alycbur_actualizada = pd.merge(data_alycbur, clientes[['CUIT', 'Oficial']], on='CUIT', how='left')
data_alycbur_actualizada

,Boleto,Concertación,Liquidación,CUIT,Cuenta,Denominación,Cartera,Categoría,Clase,Tipo de operación,...,Aranceles,Impuestos,Otros,Tipo de cambio,Administrador,Operador,Situación,Número de Operacion,Empresa,Oficial
0,BOL 2021000055,2021-01-04,2021-01-04,30600725447,500062,"ROWING SA o ROMAN, JESICA",[GRUPO 5] GRUPO 5,NaN,NaN,ECHEQ - Subasta,...,"ARS 11005,06","ARS 15764,50",0,NaN,NaN,NaN,/ARS/,1084,ALYCBUR,ASISTENCIA COMERCIAL
1,BOL 2021000058,2021-01-04,2021-01-04,30600725447,500062,"ROWING SA o ROMAN, JESICA",[GRUPO 5] GRUPO 5,NaN,NaN,ECHEQ - Subasta,...,"ARS 5502,64","ARS 5466,29",0,NaN,NaN,NaN,/ARS/,1085,ALYCBUR,ASISTENCIA COMERCIAL
2,BOL 2021000060,2021-01-04,2021-01-04,30600725447,500062,"ROWING SA o ROMAN, JESICA",[GRUPO 5] GRUPO 5,NaN,NaN,ECHEQ - Subasta,...,"ARS 5514,52","ARS 5546,40",0,NaN,NaN,NaN,/ARS/,1086,ALYCBUR,ASISTENCIA COMERCIAL
3,BOL 2021000062,2021-01-04,2021-01-04,30600725447,500062,"ROWING SA o ROMAN, JESICA",[GRUPO 5] GRUPO 5,NaN,NaN,ECHEQ - Subasta,...,"ARS 7717,60","ARS 7857,53",0,NaN,NaN,NaN,/ARS/,1087,ALYCBUR,ASISTENCIA COMERCIAL
4,BOL 2021000064,2021-01-04,2021-01-04,30600725447,500062,"ROWING SA o ROMAN, JESICA",[GRUPO 5] GRUPO 5,NaN,NaN,ECHEQ - Subasta,...,"ARS 7717,60","ARS 8141,88",0,NaN,NaN,NaN,/ARS/,1088,ALYCBUR,ASISTENCIA COMERCIAL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5710,BOL 2023005986,2023-03-03,2023-03-03,30708442409,500040,MAXIMIA SA,[GRUPO 5] GRUPO 5,NaN,NaN,ECHEQ - Subasta,...,"ARS 29767,94","ARS 6281,99",0,NaN,NaN,NaN,/ARS/,109502,ALYCBUR,ASISTENCIA COMERCIAL
5711,BOL 2023006022,2023-03-03,2023-03-06,30707805338,500226,ATLANTIDA DIGITAL S.A.,[GRUPO 5] GRUPO 5,NaN,NaN,ECHEQ - Subasta,...,"ARS 5000,00","ARS 1082,93",0,NaN,NaN,NaN,/ARS/,109528,ALYCBUR,ASISTENCIA COMERCIAL
5712,BOL 2023006023,2023-03-03,2023-03-06,30707805338,500226,ATLANTIDA DIGITAL S.A.,[GRUPO 5] GRUPO 5,NaN,NaN,ECHEQ - Subasta,...,"ARS 5000,00","ARS 1078,87",0,NaN,NaN,NaN,/ARS/,109529,ALYCBUR,ASISTENCIA COMERCIAL
5713,BOL 2023006025,2023-03-03,2023-03-06,30707805338,500226,ATLANTIDA DIGITAL S.A.,[GRUPO 5] GRUPO 5,NaN,NaN,ECHEQ - Subasta,...,"ARS 5000,00","ARS 1074,70",0,NaN,NaN,NaN,/ARS/,109531,ALYCBUR,ASISTENCIA COMERCIAL
5714,BOL 2023006026,2023-03-03,2023-03-06,30707805338,500226,ATLANTIDA DIGITAL S.A.,[GRUPO 5] GRUPO 5,NaN,NaN,ECHEQ - Subasta,...,"ARS 2500,00","ARS 543,44",0,NaN,NaN,NaN,/ARS/,109532,ALYCBUR,ASISTENCIA COMERCIAL

In [7]:
columnas = {
    'Boleto': 'Boleto / Operación',
    'Cuenta': 'N° Cliente',
    'Denominación': 'Cliente',
    'Precio': 'Tasa',
    'Aranceles': 'Gastos',
    'Bruto': 'Bruto_alycbur'
}

data_alycbur_actualizada = data_alycbur_actualizada.rename(columns=columnas)
data_alycbur_actualizada

,Boleto / Operación,Concertación,Liquidación,CUIT,N° Cliente,Cliente,Cartera,Categoría,Clase,Tipo de operación,...,Gastos,Impuestos,Otros,Tipo de cambio,Administrador,Operador,Situación,Número de Operacion,Empresa,Oficial
0,BOL 2021000055,2021-01-04,2021-01-04,30600725447,500062,"ROWING SA o ROMAN, JESICA",[GRUPO 5] GRUPO 5,NaN,NaN,ECHEQ - Subasta,...,"ARS 11005,06","ARS 15764,50",0,NaN,NaN,NaN,/ARS/,1084,ALYCBUR,ASISTENCIA COMERCIAL
1,BOL 2021000058,2021-01-04,2021-01-04,30600725447,500062,"ROWING SA o ROMAN, JESICA",[GRUPO 5] GRUPO 5,NaN,NaN,ECHEQ - Subasta,...,"ARS 5502,64","ARS 5466,29",0,NaN,NaN,NaN,/ARS/,1085,ALYCBUR,ASISTENCIA COMERCIAL
2,BOL 2021000060,2021-01-04,2021-01-04,30600725447,500062,"ROWING SA o ROMAN, JESICA",[GRUPO 5] GRUPO 5,NaN,NaN,ECHEQ - Subasta,...,"ARS 5514,52","ARS 5546,40",0,NaN,NaN,NaN,/ARS/,1086,ALYCBUR,ASISTENCIA COMERCIAL
3,BOL 2021000062,2021-01-04,2021-01-04,30600725447,500062,"ROWING SA o ROMAN, JESICA",[GRUPO 5] GRUPO 5,NaN,NaN,ECHEQ - Subasta,...,"ARS 7717,60","ARS 7857,53",0,NaN,NaN,NaN,/ARS/,1087,ALYCBUR,ASISTENCIA COMERCIAL
4,BOL 2021000064,2021-01-04,2021-01-04,30600725447,500062,"ROWING SA o ROMAN, JESICA",[GRUPO 5] GRUPO 5,NaN,NaN,ECHEQ - Subasta,...,"ARS 7717,60","ARS 8141,88",0,NaN,NaN,NaN,/ARS/,1088,ALYCBUR,ASISTENCIA COMERCIAL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5710,BOL 2023005986,2023-03-03,2023-03-03,30708442409,500040,MAXIMIA SA,[GRUPO 5] GRUPO 5,NaN,NaN,ECHEQ - Subasta,...,"ARS 29767,94","ARS 6281,99",0,NaN,NaN,NaN,/ARS/,109502,ALYCBUR,ASISTENCIA COMERCIAL
5711,BOL 2023006022,2023-03-03,2023-03-06,30707805338,500226,ATLANTIDA DIGITAL S.A.,[GRUPO 5] GRUPO 5,NaN,NaN,ECHEQ - Subasta,...,"ARS 5000,00","ARS 1082,93",0,NaN,NaN,NaN,/ARS/,109528,ALYCBUR,ASISTENCIA COMERCIAL
5712,BOL 2023006023,2023-03-03,2023-03-06,30707805338,500226,ATLANTIDA DIGITAL S.A.,[GRUPO 5] GRUPO 5,NaN,NaN,ECHEQ - Subasta,...,"ARS 5000,00","ARS 1078,87",0,NaN,NaN,NaN,/ARS/,109529,ALYCBUR,ASISTENCIA COMERCIAL
5713,BOL 2023006025,2023-03-03,2023-03-06,30707805338,500226,ATLANTIDA DIGITAL S.A.,[GRUPO 5] GRUPO 5,NaN,NaN,ECHEQ - Subasta,...,"ARS 5000,00","ARS 1074,70",0,NaN,NaN,NaN,/ARS/,109531,ALYCBUR,ASISTENCIA COMERCIAL
5714,BOL 2023006026,2023-03-03,2023-03-06,30707805338,500226,ATLANTIDA DIGITAL S.A.,[GRUPO 5] GRUPO 5,NaN,NaN,ECHEQ - Subasta,...,"ARS 2500,00","ARS 543,44",0,NaN,NaN,NaN,/ARS/,109532,ALYCBUR,ASISTENCIA COMERCIAL

In [8]:
data_alycbur_actualizada_2 = pd.merge(data_alycbur_actualizada, clientes[['CUIT', 'Ubicación']], on='CUIT', how='left')
data_alycbur_actualizada_2

,Boleto / Operación,Concertación,Liquidación,CUIT,N° Cliente,Cliente,Cartera,Categoría,Clase,Tipo de operación,...,Impuestos,Otros,Tipo de cambio,Administrador,Operador,Situación,Número de Operacion,Empresa,Oficial,Ubicación
0,BOL 2021000055,2021-01-04,2021-01-04,30600725447,500062,"ROWING SA o ROMAN, JESICA",[GRUPO 5] GRUPO 5,NaN,NaN,ECHEQ - Subasta,...,"ARS 15764,50",0,NaN,NaN,NaN,/ARS/,1084,ALYCBUR,ASISTENCIA COMERCIAL,"Buenos Aires, Argentina"
1,BOL 2021000058,2021-01-04,2021-01-04,30600725447,500062,"ROWING SA o ROMAN, JESICA",[GRUPO 5] GRUPO 5,NaN,NaN,ECHEQ - Subasta,...,"ARS 5466,29",0,NaN,NaN,NaN,/ARS/,1085,ALYCBUR,ASISTENCIA COMERCIAL,"Buenos Aires, Argentina"
2,BOL 2021000060,2021-01-04,2021-01-04,30600725447,500062,"ROWING SA o ROMAN, JESICA",[GRUPO 5] GRUPO 5,NaN,NaN,ECHEQ - Subasta,...,"ARS 5546,40",0,NaN,NaN,NaN,/ARS/,1086,ALYCBUR,ASISTENCIA COMERCIAL,"Buenos Aires, Argentina"
3,BOL 2021000062,2021-01-04,2021-01-04,30600725447,500062,"ROWING SA o ROMAN, JESICA",[GRUPO 5] GRUPO 5,NaN,NaN,ECHEQ - Subasta,...,"ARS 7857,53",0,NaN,NaN,NaN,/ARS/,1087,ALYCBUR,ASISTENCIA COMERCIAL,"Buenos Aires, Argentina"
4,BOL 2021000064,2021-01-04,2021-01-04,30600725447,500062,"ROWING SA o ROMAN, JESICA",[GRUPO 5] GRUPO 5,NaN,NaN,ECHEQ - Subasta,...,"ARS 8141,88",0,NaN,NaN,NaN,/ARS/,1088,ALYCBUR,ASISTENCIA COMERCIAL,"Buenos Aires, Argentina"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5710,BOL 2023005986,2023-03-03,2023-03-03,30708442409,500040,MAXIMIA SA,[GRUPO 5] GRUPO 5,NaN,NaN,ECHEQ - Subasta,...,"ARS 6281,99",0,NaN,NaN,NaN,/ARS/,109502,ALYCBUR,ASISTENCIA COMERCIAL,"Buenos Aires, Argentina"
5711,BOL 2023006022,2023-03-03,2023-03-06,30707805338,500226,ATLANTIDA DIGITAL S.A.,[GRUPO 5] GRUPO 5,NaN,NaN,ECHEQ - Subasta,...,"ARS 1082,93",0,NaN,NaN,NaN,/ARS/,109528,ALYCBUR,ASISTENCIA COMERCIAL,"Buenos Aires, Argentina"
5712,BOL 2023006023,2023-03-03,2023-03-06,30707805338,500226,ATLANTIDA DIGITAL S.A.,[GRUPO 5] GRUPO 5,NaN,NaN,ECHEQ - Subasta,...,"ARS 1078,87",0,NaN,NaN,NaN,/ARS/,109529,ALYCBUR,ASISTENCIA COMERCIAL,"Buenos Aires, Argentina"
5713,BOL 2023006025,2023-03-03,2023-03-06,30707805338,500226,ATLANTIDA DIGITAL S.A.,[GRUPO 5] GRUPO 5,NaN,NaN,ECHEQ - Subasta,...,"ARS 1074,70",0,NaN,NaN,NaN,/ARS/,109531,ALYCBUR,ASISTENCIA COMERCIAL,"Buenos Aires, Argentina"
5714,BOL 2023006026,2023-03-03,2023-03-06,30707805338,500226,ATLANTIDA DIGITAL S.A.,[GRUPO 5] GRUPO 5,NaN,NaN,ECHEQ - Subasta,...,"ARS 543,44",0,NaN,NaN,NaN,/ARS/,109532,ALYCBUR,ASISTENCIA COMERCIAL,"Buenos Aires, Argentina"

In [9]:
data_alycbur_actualizada_3 = pd.merge(data_alycbur_actualizada_2, clientes[['CUIT', 'Grupo / Cliente']], on='CUIT', how='left')
data_alycbur_actualizada_3

,Boleto / Operación,Concertación,Liquidación,CUIT,N° Cliente,Cliente,Cartera,Categoría,Clase,Tipo de operación,...,Otros,Tipo de cambio,Administrador,Operador,Situación,Número de Operacion,Empresa,Oficial,Ubicación,Grupo / Cliente
0,BOL 2021000055,2021-01-04,2021-01-04,30600725447,500062,"ROWING SA o ROMAN, JESICA",[GRUPO 5] GRUPO 5,NaN,NaN,ECHEQ - Subasta,...,0,NaN,NaN,NaN,/ARS/,1084,ALYCBUR,ASISTENCIA COMERCIAL,"Buenos Aires, Argentina","ROWING SA o ROMAN, JESICA"
1,BOL 2021000058,2021-01-04,2021-01-04,30600725447,500062,"ROWING SA o ROMAN, JESICA",[GRUPO 5] GRUPO 5,NaN,NaN,ECHEQ - Subasta,...,0,NaN,NaN,NaN,/ARS/,1085,ALYCBUR,ASISTENCIA COMERCIAL,"Buenos Aires, Argentina","ROWING SA o ROMAN, JESICA"
2,BOL 2021000060,2021-01-04,2021-01-04,30600725447,500062,"ROWING SA o ROMAN, JESICA",[GRUPO 5] GRUPO 5,NaN,NaN,ECHEQ - Subasta,...,0,NaN,NaN,NaN,/ARS/,1086,ALYCBUR,ASISTENCIA COMERCIAL,"Buenos Aires, Argentina","ROWING SA o ROMAN, JESICA"
3,BOL 2021000062,2021-01-04,2021-01-04,30600725447,500062,"ROWING SA o ROMAN, JESICA",[GRUPO 5] GRUPO 5,NaN,NaN,ECHEQ - Subasta,...,0,NaN,NaN,NaN,/ARS/,1087,ALYCBUR,ASISTENCIA COMERCIAL,"Buenos Aires, Argentina","ROWING SA o ROMAN, JESICA"
4,BOL 2021000064,2021-01-04,2021-01-04,30600725447,500062,"ROWING SA o ROMAN, JESICA",[GRUPO 5] GRUPO 5,NaN,NaN,ECHEQ - Subasta,...,0,NaN,NaN,NaN,/ARS/,1088,ALYCBUR,ASISTENCIA COMERCIAL,"Buenos Aires, Argentina","ROWING SA o ROMAN, JESICA"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5710,BOL 2023005986,2023-03-03,2023-03-03,30708442409,500040,MAXIMIA SA,[GRUPO 5] GRUPO 5,NaN,NaN,ECHEQ - Subasta,...,0,NaN,NaN,NaN,/ARS/,109502,ALYCBUR,ASISTENCIA COMERCIAL,"Buenos Aires, Argentina",MAXIMIA SA
5711,BOL 2023006022,2023-03-03,2023-03-06,30707805338,500226,ATLANTIDA DIGITAL S.A.,[GRUPO 5] GRUPO 5,NaN,NaN,ECHEQ - Subasta,...,0,NaN,NaN,NaN,/ARS/,109528,ALYCBUR,ASISTENCIA COMERCIAL,"Buenos Aires, Argentina",GRUPO ATLANTIDA
5712,BOL 2023006023,2023-03-03,2023-03-06,30707805338,500226,ATLANTIDA DIGITAL S.A.,[GRUPO 5] GRUPO 5,NaN,NaN,ECHEQ - Subasta,...,0,NaN,NaN,NaN,/ARS/,109529,ALYCBUR,ASISTENCIA COMERCIAL,"Buenos Aires, Argentina",GRUPO ATLANTIDA
5713,BOL 2023006025,2023-03-03,2023-03-06,30707805338,500226,ATLANTIDA DIGITAL S.A.,[GRUPO 5] GRUPO 5,NaN,NaN,ECHEQ - Subasta,...,0,NaN,NaN,NaN,/ARS/,109531,ALYCBUR,ASISTENCIA COMERCIAL,"Buenos Aires, Argentina",GRUPO ATLANTIDA
5714,BOL 2023006026,2023-03-03,2023-03-06,30707805338,500226,ATLANTIDA DIGITAL S.A.,[GRUPO 5] GRUPO 5,NaN,NaN,ECHEQ - Subasta,...,0,NaN,NaN,NaN,/ARS/,109532,ALYCBUR,ASISTENCIA COMERCIAL,"Buenos Aires, Argentina",GRUPO ATLANTIDA

In [10]:
operaciones

   Empresa  Tipo de operación Categorias
0  Finares               L CH     CHEQUE
1  Finares               L DC    FACTURA
2  Alycbur     ECHEQ - Compra     CHEQUE
3  Alycbur    ECHEQ - Subasta     CHEQUE
4  Alycbur  Pagarés - Subasta     PAGARÉ
5  Alycbur      FCE - Subasta    FACTURA
6  Alycbur      CPD - Subasta     CHEQUE

In [11]:
data_alycbur_final = pd.merge(data_alycbur_actualizada_3, operaciones[['Tipo de operación', 'Categorias']], on='Tipo de operación', how='left')
data_alycbur_final = data_alycbur_final.drop(columns=['Tipo de operación'])
data_alycbur_final

,Boleto / Operación,Concertación,Liquidación,CUIT,N° Cliente,Cliente,Cartera,Categoría,Clase,Instrumento,...,Tipo de cambio,Administrador,Operador,Situación,Número de Operacion,Empresa,Oficial,Ubicación,Grupo / Cliente,Categorias
0,BOL 2021000055,2021-01-04,2021-01-04,30600725447,500062,"ROWING SA o ROMAN, JESICA",[GRUPO 5] GRUPO 5,NaN,NaN,[*MAV310300024] *MAV310300024 Nro. 20457088 Vt...,...,NaN,NaN,NaN,/ARS/,1084,ALYCBUR,ASISTENCIA COMERCIAL,"Buenos Aires, Argentina","ROWING SA o ROMAN, JESICA",CHEQUE
1,BOL 2021000058,2021-01-04,2021-01-04,30600725447,500062,"ROWING SA o ROMAN, JESICA",[GRUPO 5] GRUPO 5,NaN,NaN,[*MAV010300033] *MAV010300033 Nro. 20457090 Vt...,...,NaN,NaN,NaN,/ARS/,1085,ALYCBUR,ASISTENCIA COMERCIAL,"Buenos Aires, Argentina","ROWING SA o ROMAN, JESICA",CHEQUE
2,BOL 2021000060,2021-01-04,2021-01-04,30600725447,500062,"ROWING SA o ROMAN, JESICA",[GRUPO 5] GRUPO 5,NaN,NaN,[*MAV020300025] *MAV020300025 Nro. 20457082 Vt...,...,NaN,NaN,NaN,/ARS/,1086,ALYCBUR,ASISTENCIA COMERCIAL,"Buenos Aires, Argentina","ROWING SA o ROMAN, JESICA",CHEQUE
3,BOL 2021000062,2021-01-04,2021-01-04,30600725447,500062,"ROWING SA o ROMAN, JESICA",[GRUPO 5] GRUPO 5,NaN,NaN,[*MAV030300033] *MAV030300033 Nro. 20457100 Vt...,...,NaN,NaN,NaN,/ARS/,1087,ALYCBUR,ASISTENCIA COMERCIAL,"Buenos Aires, Argentina","ROWING SA o ROMAN, JESICA",CHEQUE
4,BOL 2021000064,2021-01-04,2021-01-04,30600725447,500062,"ROWING SA o ROMAN, JESICA",[GRUPO 5] GRUPO 5,NaN,NaN,[*MAV040300023] *MAV040300023 Nro. 20457083 Vt...,...,NaN,NaN,NaN,/ARS/,1088,ALYCBUR,ASISTENCIA COMERCIAL,"Buenos Aires, Argentina","ROWING SA o ROMAN, JESICA",CHEQUE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5710,BOL 2023005986,2023-03-03,2023-03-03,30708442409,500040,MAXIMIA SA,[GRUPO 5] GRUPO 5,NaN,NaN,[*MAV040400323] *MAV040400323 Nro. 0 Vto. 10/0...,...,NaN,NaN,NaN,/ARS/,109502,ALYCBUR,ASISTENCIA COMERCIAL,"Buenos Aires, Argentina",MAXIMIA SA,CHEQUE
5711,BOL 2023006022,2023-03-03,2023-03-06,30707805338,500226,ATLANTIDA DIGITAL S.A.,[GRUPO 5] GRUPO 5,NaN,NaN,[*TRD250400004] *TRD250400004 Nro. 0 Vto. 27/0...,...,NaN,NaN,NaN,/ARS/,109528,ALYCBUR,ASISTENCIA COMERCIAL,"Buenos Aires, Argentina",GRUPO ATLANTIDA,CHEQUE
5712,BOL 2023006023,2023-03-03,2023-03-06,30707805338,500226,ATLANTIDA DIGITAL S.A.,[GRUPO 5] GRUPO 5,NaN,NaN,[*TRD180400011] *TRD180400011 Nro. 0 Vto. 20/0...,...,NaN,NaN,NaN,/ARS/,109529,ALYCBUR,ASISTENCIA COMERCIAL,"Buenos Aires, Argentina",GRUPO ATLANTIDA,CHEQUE
5713,BOL 2023006025,2023-03-03,2023-03-06,30707805338,500226,ATLANTIDA DIGITAL S.A.,[GRUPO 5] GRUPO 5,NaN,NaN,[*TRD110400006] *TRD110400006 Nro. 0 Vto. 13/0...,...,NaN,NaN,NaN,/ARS/,109531,ALYCBUR,ASISTENCIA COMERCIAL,"Buenos Aires, Argentina",GRUPO ATLANTIDA,CHEQUE
5714,BOL 2023006026,2023-03-03,2023-03-06,30707805338,500226,ATLANTIDA DIGITAL S.A.,[GRUPO 5] GRUPO 5,NaN,NaN,[*TRD020500005] *TRD020500005 Nro. 0 Vto. 04/0...,...,NaN,NaN,NaN,/ARS/,109532,ALYCBUR,ASISTENCIA COMERCIAL,"Buenos Aires, Argentina",GRUPO ATLANTIDA,CHEQUE

In [12]:
data_alycbur_final = data_alycbur_final.rename(columns={'Categorias': 'Tipo de operación'})
data_alycbur_final

,Boleto / Operación,Concertación,Liquidación,CUIT,N° Cliente,Cliente,Cartera,Categoría,Clase,Instrumento,...,Tipo de cambio,Administrador,Operador,Situación,Número de Operacion,Empresa,Oficial,Ubicación,Grupo / Cliente,Tipo de operación
0,BOL 2021000055,2021-01-04,2021-01-04,30600725447,500062,"ROWING SA o ROMAN, JESICA",[GRUPO 5] GRUPO 5,NaN,NaN,[*MAV310300024] *MAV310300024 Nro. 20457088 Vt...,...,NaN,NaN,NaN,/ARS/,1084,ALYCBUR,ASISTENCIA COMERCIAL,"Buenos Aires, Argentina","ROWING SA o ROMAN, JESICA",CHEQUE
1,BOL 2021000058,2021-01-04,2021-01-04,30600725447,500062,"ROWING SA o ROMAN, JESICA",[GRUPO 5] GRUPO 5,NaN,NaN,[*MAV010300033] *MAV010300033 Nro. 20457090 Vt...,...,NaN,NaN,NaN,/ARS/,1085,ALYCBUR,ASISTENCIA COMERCIAL,"Buenos Aires, Argentina","ROWING SA o ROMAN, JESICA",CHEQUE
2,BOL 2021000060,2021-01-04,2021-01-04,30600725447,500062,"ROWING SA o ROMAN, JESICA",[GRUPO 5] GRUPO 5,NaN,NaN,[*MAV020300025] *MAV020300025 Nro. 20457082 Vt...,...,NaN,NaN,NaN,/ARS/,1086,ALYCBUR,ASISTENCIA COMERCIAL,"Buenos Aires, Argentina","ROWING SA o ROMAN, JESICA",CHEQUE
3,BOL 2021000062,2021-01-04,2021-01-04,30600725447,500062,"ROWING SA o ROMAN, JESICA",[GRUPO 5] GRUPO 5,NaN,NaN,[*MAV030300033] *MAV030300033 Nro. 20457100 Vt...,...,NaN,NaN,NaN,/ARS/,1087,ALYCBUR,ASISTENCIA COMERCIAL,"Buenos Aires, Argentina","ROWING SA o ROMAN, JESICA",CHEQUE
4,BOL 2021000064,2021-01-04,2021-01-04,30600725447,500062,"ROWING SA o ROMAN, JESICA",[GRUPO 5] GRUPO 5,NaN,NaN,[*MAV040300023] *MAV040300023 Nro. 20457083 Vt...,...,NaN,NaN,NaN,/ARS/,1088,ALYCBUR,ASISTENCIA COMERCIAL,"Buenos Aires, Argentina","ROWING SA o ROMAN, JESICA",CHEQUE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5710,BOL 2023005986,2023-03-03,2023-03-03,30708442409,500040,MAXIMIA SA,[GRUPO 5] GRUPO 5,NaN,NaN,[*MAV040400323] *MAV040400323 Nro. 0 Vto. 10/0...,...,NaN,NaN,NaN,/ARS/,109502,ALYCBUR,ASISTENCIA COMERCIAL,"Buenos Aires, Argentina",MAXIMIA SA,CHEQUE
5711,BOL 2023006022,2023-03-03,2023-03-06,30707805338,500226,ATLANTIDA DIGITAL S.A.,[GRUPO 5] GRUPO 5,NaN,NaN,[*TRD250400004] *TRD250400004 Nro. 0 Vto. 27/0...,...,NaN,NaN,NaN,/ARS/,109528,ALYCBUR,ASISTENCIA COMERCIAL,"Buenos Aires, Argentina",GRUPO ATLANTIDA,CHEQUE
5712,BOL 2023006023,2023-03-03,2023-03-06,30707805338,500226,ATLANTIDA DIGITAL S.A.,[GRUPO 5] GRUPO 5,NaN,NaN,[*TRD180400011] *TRD180400011 Nro. 0 Vto. 20/0...,...,NaN,NaN,NaN,/ARS/,109529,ALYCBUR,ASISTENCIA COMERCIAL,"Buenos Aires, Argentina",GRUPO ATLANTIDA,CHEQUE
5713,BOL 2023006025,2023-03-03,2023-03-06,30707805338,500226,ATLANTIDA DIGITAL S.A.,[GRUPO 5] GRUPO 5,NaN,NaN,[*TRD110400006] *TRD110400006 Nro. 0 Vto. 13/0...,...,NaN,NaN,NaN,/ARS/,109531,ALYCBUR,ASISTENCIA COMERCIAL,"Buenos Aires, Argentina",GRUPO ATLANTIDA,CHEQUE
5714,BOL 2023006026,2023-03-03,2023-03-06,30707805338,500226,ATLANTIDA DIGITAL S.A.,[GRUPO 5] GRUPO 5,NaN,NaN,[*TRD020500005] *TRD020500005 Nro. 0 Vto. 04/0...,...,NaN,NaN,NaN,/ARS/,109532,ALYCBUR,ASISTENCIA COMERCIAL,"Buenos Aires, Argentina",GRUPO ATLANTIDA,CHEQUE

In [13]:
data_alycbur_final[~data_alycbur_final['Tipo de cambio'].isnull()]

,Boleto / Operación,Concertación,Liquidación,CUIT,N° Cliente,Cliente,Cartera,Categoría,Clase,Instrumento,...,Tipo de cambio,Administrador,Operador,Situación,Número de Operacion,Empresa,Oficial,Ubicación,Grupo / Cliente,Tipo de operación
145,BOL 2021002043,2021-02-03,2021-02-03,30708809876,500059,REXYS SA,[GRUPO 5] GRUPO 5,NaN,NaN,[%UM0220200001] %UM0220200001 Nro. Vto. 24/02...,...,"T.C.: USD 1 = ARS 92,50",NaN,NaN,/USD/,3645,ALYCBUR,ASISTENCIA COMERCIAL,"Buenos Aires, Argentina",REXYS SA,FACTURA
3481,BOL 2022015918,2022-07-01,2022-07-01,30711827923,500106,FIXON GROUP SA,[GRUPO 5] GRUPO 5,NaN,NaN,[*MAV140900258] *MAV140900258 Nro. Vto. 16/09...,...,"T.C.: USDB 1 = ARS 125,215",0207 - Alycbur S.A.,NaN,/ARS/,64218,ALYCBUR,CLAUDIA GALLARDO,"Provincia de Entre Ríos, Argentina",GRUPO FIXON,CHEQUE
3482,BOL 2022015920,2022-07-01,2022-07-01,30711827923,500106,FIXON GROUP SA,[GRUPO 5] GRUPO 5,NaN,NaN,[*MAV150900254] *MAV150900254 Nro. Vto. 19/09...,...,"T.C.: USDB 1 = ARS 125,215",0207 - Alycbur S.A.,NaN,/ARS/,64220,ALYCBUR,CLAUDIA GALLARDO,"Provincia de Entre Ríos, Argentina",GRUPO FIXON,CHEQUE
3483,BOL 2022015925,2022-07-01,2022-07-01,30716206897,500175,FRESCOVO SAS,[GRUPO 5] GRUPO 5,NaN,NaN,[*MAV190900084] *MAV190900084 Nro. 0 Vto. 21/0...,...,"T.C.: USDB 1 = ARS 125,215",NaN,NaN,/ARS/,64225,ALYCBUR,ASISTENCIA COMERCIAL,"Buenos Aires, Argentina",FRESCOVO SAS,CHEQUE
3484,BOL 2022015926,2022-07-01,2022-07-01,30711827923,500106,FIXON GROUP SA,[GRUPO 5] GRUPO 5,NaN,NaN,[*MAV160900274] *MAV160900274 Nro. Vto. 20/09...,...,"T.C.: USDB 1 = ARS 125,215",0207 - Alycbur S.A.,NaN,/ARS/,64226,ALYCBUR,CLAUDIA GALLARDO,"Provincia de Entre Ríos, Argentina",GRUPO FIXON,CHEQUE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5605,BOL 2023004821,2023-02-17,2023-02-17,30518293687,500206,COOPERATIVA DE TABACALEROS DE JUJUY LIMITADA,[GRUPO 5] GRUPO 5,NaN,NaN,[#UMV140430013] #UMV140430013 Nro. 38165 Vto. ...,...,"T.C.: USDB 1 = ARS 192,7833",NaN,NaN,/USDB/,107773,ALYCBUR,CAROLINA GARCÍA,"Jujuy, Argentina",COOPERATIVA DE TABACALEROS DE JUJUY LIMITADA,PAGARÉ
5619,BOL 2023005205,2023-02-24,2023-02-24,30518293687,500206,COOPERATIVA DE TABACALEROS DE JUJUY LIMITADA,[GRUPO 5] GRUPO 5,NaN,NaN,[#UMV210430009] #UMV210430009 Nro. 38407 Vto. ...,...,"T.C.: USDB 1 = ARS 195,35",NaN,NaN,/USDB/,108339,ALYCBUR,CAROLINA GARCÍA,"Jujuy, Argentina",COOPERATIVA DE TABACALEROS DE JUJUY LIMITADA,PAGARÉ
5656,BOL 2023005602,2023-03-01,2023-03-01,30712013962,500193,WORMS ARGENTINA S.A,[GRUPO 5] GRUPO 5,NaN,NaN,[#UMV100730044] #UMV100730044 Nro. 38671 Vto. ...,...,"T.C.: USDB 1 = ARS 197,1533",NaN,NaN,/USDB/,108957,ALYCBUR,ASISTENCIA COMERCIAL,"Provincia de Corrientes, Argentina",GRUPO WORMS,PAGARÉ
5695,BOL 2023005954,2023-03-03,2023-03-03,30504005085,500376,FRIAR SA,[GRUPO 5] GRUPO 5,NaN,NaN,[#UMV020530010] #UMV020530010 Nro. 38798 Vto. ...,...,"T.C.: USDB 1 = ARS 197,8867",NaN,NaN,/USDB/,109470,ALYCBUR,ASISTENCIA COMERCIAL,"Santa Fe, Argentina",FRIAR SA,PAGARÉ
5703,BOL 2023005970,2023-03-03,2023-03-03,33707480519,500400,EMELKA SA,[GRUPO 5] GRUPO 5,NaN,NaN,[#UMV010630011] #UMV010630011 Nro. 38775 Vto. ...,...,"T.C.: USDB 1 = ARS 197,8867",NaN,NaN,/USDB/,109486,ALYCBUR,NaN,NaN,NaN,PAGARÉ

In [14]:
data_alycbur_final['Tipo de cambio'] = data_alycbur_final['Tipo de cambio'].astype(str)

In [15]:
data_alycbur_final['Tipo de cambio'] = data_alycbur_final['Tipo de cambio'].str.extract(r'ARS\s(\d+\,?\d*)', expand=False)
data_alycbur_final['Tipo de cambio'] = data_alycbur_final['Tipo de cambio'].str.replace(',', '.').astype(float)
data_alycbur_final['Tipo de cambio'] = data_alycbur_final['Tipo de cambio'].fillna(0)

In [16]:
data_alycbur_final = data_alycbur_final.rename(columns={'Tipo de cambio': 'TC usado', 'Cantidad': 'Bruto (no usar)'})
data_alycbur_final

,Boleto / Operación,Concertación,Liquidación,CUIT,N° Cliente,Cliente,Cartera,Categoría,Clase,Instrumento,...,TC usado,Administrador,Operador,Situación,Número de Operacion,Empresa,Oficial,Ubicación,Grupo / Cliente,Tipo de operación
0,BOL 2021000055,2021-01-04,2021-01-04,30600725447,500062,"ROWING SA o ROMAN, JESICA",[GRUPO 5] GRUPO 5,NaN,NaN,[*MAV310300024] *MAV310300024 Nro. 20457088 Vt...,...,0.0,NaN,NaN,/ARS/,1084,ALYCBUR,ASISTENCIA COMERCIAL,"Buenos Aires, Argentina","ROWING SA o ROMAN, JESICA",CHEQUE
1,BOL 2021000058,2021-01-04,2021-01-04,30600725447,500062,"ROWING SA o ROMAN, JESICA",[GRUPO 5] GRUPO 5,NaN,NaN,[*MAV010300033] *MAV010300033 Nro. 20457090 Vt...,...,0.0,NaN,NaN,/ARS/,1085,ALYCBUR,ASISTENCIA COMERCIAL,"Buenos Aires, Argentina","ROWING SA o ROMAN, JESICA",CHEQUE
2,BOL 2021000060,2021-01-04,2021-01-04,30600725447,500062,"ROWING SA o ROMAN, JESICA",[GRUPO 5] GRUPO 5,NaN,NaN,[*MAV020300025] *MAV020300025 Nro. 20457082 Vt...,...,0.0,NaN,NaN,/ARS/,1086,ALYCBUR,ASISTENCIA COMERCIAL,"Buenos Aires, Argentina","ROWING SA o ROMAN, JESICA",CHEQUE
3,BOL 2021000062,2021-01-04,2021-01-04,30600725447,500062,"ROWING SA o ROMAN, JESICA",[GRUPO 5] GRUPO 5,NaN,NaN,[*MAV030300033] *MAV030300033 Nro. 20457100 Vt...,...,0.0,NaN,NaN,/ARS/,1087,ALYCBUR,ASISTENCIA COMERCIAL,"Buenos Aires, Argentina","ROWING SA o ROMAN, JESICA",CHEQUE
4,BOL 2021000064,2021-01-04,2021-01-04,30600725447,500062,"ROWING SA o ROMAN, JESICA",[GRUPO 5] GRUPO 5,NaN,NaN,[*MAV040300023] *MAV040300023 Nro. 20457083 Vt...,...,0.0,NaN,NaN,/ARS/,1088,ALYCBUR,ASISTENCIA COMERCIAL,"Buenos Aires, Argentina","ROWING SA o ROMAN, JESICA",CHEQUE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5710,BOL 2023005986,2023-03-03,2023-03-03,30708442409,500040,MAXIMIA SA,[GRUPO 5] GRUPO 5,NaN,NaN,[*MAV040400323] *MAV040400323 Nro. 0 Vto. 10/0...,...,0.0,NaN,NaN,/ARS/,109502,ALYCBUR,ASISTENCIA COMERCIAL,"Buenos Aires, Argentina",MAXIMIA SA,CHEQUE
5711,BOL 2023006022,2023-03-03,2023-03-06,30707805338,500226,ATLANTIDA DIGITAL S.A.,[GRUPO 5] GRUPO 5,NaN,NaN,[*TRD250400004] *TRD250400004 Nro. 0 Vto. 27/0...,...,0.0,NaN,NaN,/ARS/,109528,ALYCBUR,ASISTENCIA COMERCIAL,"Buenos Aires, Argentina",GRUPO ATLANTIDA,CHEQUE
5712,BOL 2023006023,2023-03-03,2023-03-06,30707805338,500226,ATLANTIDA DIGITAL S.A.,[GRUPO 5] GRUPO 5,NaN,NaN,[*TRD180400011] *TRD180400011 Nro. 0 Vto. 20/0...,...,0.0,NaN,NaN,/ARS/,109529,ALYCBUR,ASISTENCIA COMERCIAL,"Buenos Aires, Argentina",GRUPO ATLANTIDA,CHEQUE
5713,BOL 2023006025,2023-03-03,2023-03-06,30707805338,500226,ATLANTIDA DIGITAL S.A.,[GRUPO 5] GRUPO 5,NaN,NaN,[*TRD110400006] *TRD110400006 Nro. 0 Vto. 13/0...,...,0.0,NaN,NaN,/ARS/,109531,ALYCBUR,ASISTENCIA COMERCIAL,"Buenos Aires, Argentina",GRUPO ATLANTIDA,CHEQUE
5714,BOL 2023006026,2023-03-03,2023-03-06,30707805338,500226,ATLANTIDA DIGITAL S.A.,[GRUPO 5] GRUPO 5,NaN,NaN,[*TRD020500005] *TRD020500005 Nro. 0 Vto. 04/0...,...,0.0,NaN,NaN,/ARS/,109532,ALYCBUR,ASISTENCIA COMERCIAL,"Buenos Aires, Argentina",GRUPO ATLANTIDA,CHEQUE

In [17]:
data_alycbur_final['Tasa'] = data_alycbur_final['Tasa'] / 100
data_alycbur_final['Bruto'] = data_alycbur_final.apply(lambda row: row['Bruto (no usar)'] * row['TC usado'] if row['Tipo de operación'] == 'PAGARÉ' else row['Bruto (no usar)'], axis=1)
data_alycbur_final['Tasa']

0       0.58
1       0.56
2       0.56
3       0.56
4       0.56
        ...
5710    0.79
5711    0.74
5712    0.74
5713    0.74
5714    0.74
Name: Tasa, Length: 5715, dtype: float64

In [18]:
data_alycbur_final['Neto'] = data_alycbur_final['Neto'].str.extract(r'ARS -(\d+\,?\d*)', expand=False)
data_alycbur_final['Neto'] = data_alycbur_final['Neto'].str.replace(',', '.').astype(float)
data_alycbur_final['Neto']

0       409396.42
1       218623.75
2       218702.20
3       305525.68
4       303887.25
          ...
5710    541306.17
5711    446075.13
5712    451981.01
5713    458042.53
5714    220159.49
Name: Neto, Length: 5715, dtype: float64

In [19]:
data_alycbur_final['Gastos'] = data_alycbur_final['Gastos'].str.extract(r'ARS (\d+\,?\d*)', expand=False)
data_alycbur_final['Gastos'] = data_alycbur_final['Gastos'].str.replace(',', '.').astype(float)
data_alycbur_final['Gastos']

0       11005.06
1        5502.64
2        5514.52
3        7717.60
4        7717.60
          ...
5710    29767.94
5711     5000.00
5712     5000.00
5713     5000.00
5714     2500.00
Name: Gastos, Length: 5715, dtype: float64

In [20]:
data_alycbur_final['Interes'] = data_alycbur_final['Bruto (no usar)'] - data_alycbur_final['Bruto_alycbur']
data_alycbur_final['Interes']

0       63802.16
1       20438.51
2       20806.47
3       29570.70
4       30918.92
          ...
5710    47497.60
5711    47685.14
5712    41802.66
5713    35765.16
5714    26709.24
Name: Interes, Length: 5715, dtype: float64

In [21]:
data_alycbur_final['Facturación'] = data_alycbur_final['Interes'] + data_alycbur_final['Gastos']
data_alycbur_final['Facturación']

0       74807.22
1       25941.15
2       26320.99
3       37288.30
4       38636.52
          ...
5710    77265.54
5711    52685.14
5712    46802.66
5713    40765.16
5714    29209.24
Name: Facturación, Length: 5715, dtype: float64

In [31]:
data_alycbur_final['Vto. instrumento'] = pd.to_datetime(data_alycbur_final['Vto. instrumento'], format='%Y/%m/%d')
data_alycbur_final['Días Promedio'] = (data_alycbur_final['Vto. instrumento'] - data_alycbur_final['Concertación'])
data_alycbur_final['Días Promedio']

0      92 days
1      58 days
2      59 days
3      60 days
4      63 days
         ...
5710   38 days
5711   55 days
5712   48 days
5713   41 days
5714   62 days
Name: Días Promedio, Length: 5715, dtype: timedelta64[ns]

In [34]:
data_alycbur_final['%G'] = data_alycbur_final['Gastos'] / data_alycbur_final['Bruto (no usar)']
data_alycbur_final['%G']

0       0.022000
1       0.022000
2       0.022000
3       0.022000
4       0.022000
          ...
5710    0.047629
5711    0.010000
5712    0.010000
5713    0.010000
5714    0.010000
Name: %G, Length: 5715, dtype: float64